//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShooterDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShooterDownloader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 繁转简失败.
        /// </summary>
        internal static string ErrChsConvertion {
            get {
                return ResourceManager.GetString("ErrChsConvertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 简转繁失败.
        /// </summary>
        internal static string ErrChtConvertion {
            get {
                return ResourceManager.GetString("ErrChtConvertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停用右键菜单功能失败.
        /// </summary>
        internal static string ErrDisableShellExt {
            get {
                return ResourceManager.GetString("ErrDisableShellExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用右键菜单功能失败.
        /// </summary>
        internal static string ErrEnableShellExt {
            get {
                return ResourceManager.GetString("ErrEnableShellExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} HTTP 连接失败: {1}.
        /// </summary>
        internal static string ErrHttpRequest {
            get {
                return ResourceManager.GetString("ErrHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} HTTP 响应失败: {1}.
        /// </summary>
        internal static string ErrHttpResponse {
            get {
                return ResourceManager.GetString("ErrHttpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕下载失败.
        /// </summary>
        internal static string ErrSubDownloadFailed {
            get {
                return ResourceManager.GetString("ErrSubDownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 获取字幕失败: {1}.
        /// </summary>
        internal static string ErrSubExtraction {
            get {
                return ResourceManager.GetString("ErrSubExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 找不到字幕.
        /// </summary>
        internal static string ErrSubNotFound {
            get {
                return ResourceManager.GetString("ErrSubNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕解压缩失败.
        /// </summary>
        internal static string ErrUnGZipFailed {
            get {
                return ResourceManager.GetString("ErrUnGZipFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 所有字幕下载完毕.
        /// </summary>
        internal static string InfoAllDownloadOk {
            get {
                return ResourceManager.GetString("InfoAllDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 繁转简成功.
        /// </summary>
        internal static string InfoChsConversionOk {
            get {
                return ResourceManager.GetString("InfoChsConversionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 简转繁成功.
        /// </summary>
        internal static string InfoChtConversionOk {
            get {
                return ResourceManager.GetString("InfoChtConversionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停用右键菜单功能成功.
        /// </summary>
        internal static string InfoDisableShellExtOk {
            get {
                return ResourceManager.GetString("InfoDisableShellExtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下载已取消.
        /// </summary>
        internal static string InfoDownloadCanceled {
            get {
                return ResourceManager.GetString("InfoDownloadCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字幕转换完成.
        /// </summary>
        internal static string InfoEasyConversionOk {
            get {
                return ResourceManager.GetString("InfoEasyConversionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用右键菜单功能成功.
        /// </summary>
        internal static string InfoEnableShellExtOk {
            get {
                return ResourceManager.GetString("InfoEnableShellExtOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 搜索字幕.
        /// </summary>
        internal static string InfoFindSub {
            get {
                return ResourceManager.GetString("InfoFindSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 工作取消.
        /// </summary>
        internal static string InfoJobCancelled {
            get {
                return ResourceManager.GetString("InfoJobCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕不用转换.
        /// </summary>
        internal static string InfoNoConversion {
            get {
                return ResourceManager.GetString("InfoNoConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 开始将字幕转为简体.
        /// </summary>
        internal static string InfoStartChsConversion {
            get {
                return ResourceManager.GetString("InfoStartChsConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 开始将字幕转为繁体.
        /// </summary>
        internal static string InfoStartChtConversion {
            get {
                return ResourceManager.GetString("InfoStartChtConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字幕下载完成.
        /// </summary>
        internal static string InfoSubDownloadOk {
            get {
                return ResourceManager.GetString("InfoSubDownloadOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 已找到 {1} 个字幕.
        /// </summary>
        internal static string InfoSubFound {
            get {
                return ResourceManager.GetString("InfoSubFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 射手网字幕下载工具.
        /// </summary>
        internal static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string ProgressError {
            get {
                return ResourceManager.GetString("ProgressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无字幕.
        /// </summary>
        internal static string ProgressNoSub {
            get {
                return ResourceManager.GetString("ProgressNoSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消下载.
        /// </summary>
        internal static string UiCancelDownload {
            get {
                return ResourceManager.GetString("UiCancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消中....
        /// </summary>
        internal static string UiCanceling {
            get {
                return ResourceManager.GetString("UiCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停用右键菜单功能.
        /// </summary>
        internal static string UiDisableShellExt {
            get {
                return ResourceManager.GetString("UiDisableShellExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用右键菜单功能.
        /// </summary>
        internal static string UiEnableShellExt {
            get {
                return ResourceManager.GetString("UiEnableShellExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始下载.
        /// </summary>
        internal static string UiStartDownload {
            get {
                return ResourceManager.GetString("UiStartDownload", resourceCulture);
            }
        }
    }
}
